#
#
# The user-driven targets are:
#
# install	- Install build-tools, scripts and configuration.
# deinstall	- Removes all files installed from the "install" target.
# format	- Formats all perl scripts with perltidy.
# manpage	- Outputs manpage section of the README.
# completions	- Install (fish) shell completions.
#
#
PROG?=		build-tools
CONF=		config.pm
SCRIPT?=	script
SRC=		build-pkg
COMPLETIONS=	completions

PREFIX?=	/usr/local
ETC=		${PREFIX}/etc
SBIN=		${PREFIX}/sbin
CFG=		${ETC}/${PROG}
SHARE=		${PREFIX}/share/${PROG}

default: .PHONY
	@echo
	@echo "Targets: install, deinstall, format, manpage"
	@echo

PERMS?=		755
install: .PHONY
.for DIR in ${CFG} ${SHARE}
	mkdir -p ${DIR}
.endfor
	install -m ${PERMS} ${SCRIPT}/* ${SHARE}
	install -m ${PERMS} ${CONF} ${CFG}
.for BIN in ${SRC}
	install -m ${PERMS} ${BIN} ${SBIN}
.endfor

deinstall: .PHONY
.for DIR in ${CFG} ${SHARE}
	rm -rf ${DIR}
.endfor
.for BIN in ${SRC}
	rm -f ${SBIN}/${BIN}
.endfor

PERLTIDY=	${PREFIX}/bin/perltidy
format: .PHONY
.if !exists(${PERLTIDY})
	@echo
	@echo "WARNING: perltidy not installed.  Install required package"
	@echo "by running pkg install p5-Test-PerlTidy."
	@echo
	@false
.endif
.for BIN in ${SRC} ${CONF}
	${PERLTIDY} -b ${BIN}
	@rm -f ${BIN}.bak ${BIN}.tdy
.endfor

BUILDPKG=	${SBIN}/build-pkg
manpage: .PHONY
.if !exists(${BUILDPKG})
	@echo
	@echo "WARNING: build-pkg not installed.  Install by running"
	@echo "make install."
	@echo
	@false
.endif
	@echo "## Manpage"
	@echo "\`\`\`"
	@${BUILDPKG} -h
	@echo "\`\`\`"

FISHDIR=	${PREFIX}/share/fish/completions
completions: .PHONY
	mkdir -p ${FISHDIR}
	install -m ${PERMS} ${COMPLETIONS}/build-pkg.fish ${FISHDIR}
