#!/bin/sh
PROG=${0##*/}
#
# Arguments/flags
#
. /usr/local/etc/pdt/Environment
PORTDIR=$_DEFAULT_PORTDIR
PORTCLEAN=0
PORTSTAT=0
PORTUP=0
PORTLOG=0
usage()
{
cat <<EOF
usage: $PROG [-d port dir] [-csu]

Arguments:
	-d	-- Target port directory ($PORTDIR)
	-l(n)	-- List (n) last SVN commit logs

Flags:
	-c	-- Clean port directory commits ($PORTCLEAN)
	-s	-- Show port directory SVN status ($PORTSTAT)
	-u	-- Update port directory ($PORTUP)
EOF
	exit 1
}
#
# Parse command-line flags
#
while getopts d:l:cshu flag
do
	case "$flag" in
		# Arguments
		d) PORTDIR="$OPTARG" ;;
		l) PORTLOG="$OPTARG" ;;
		# Flags
		c) PORTCLEAN=1 ;;
		s) PORTSTAT=1 ;;
		u) PORTUP=1 ;;
		# Default
		h|*) usage ;;
	esac
done
#
#
#
[ "$#" -lt 1 ] && usage
[ ! -d "$PORTDIR" ] && die "Port directory '$PORTDIR' does not exist"
#
#
#
[ "$PORTSTAT" = 1 ] && svn status "$PORTDIR"
[ "$PORTCLEAN" = 1 ] && svn revert -R "$PORTDIR"
[ "$PORTUP" = 1 ] && svn update "$PORTDIR"
[ "$PORTLOG" -gt 0 ] && svn log -l"$PORTLOG" "$PORTDIR"
